"""add column code_highlight_style

Revision ID: 3f4441b198b0
Revises: babdd3ec9106
Create Date: 2020-06-25 16:44:38.514764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4441b198b0'
down_revision = 'babdd3ec9106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('code_highlight_style', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'code_highlight_style')
    # ### end Alembic commands ###
